class DeductionDetails:
    companyId: str
    employeeId: str
    deductionCode: str
    effectiveFrom: datetime
    endDate: datetime
    totalContribution: Optional[Decimal]
    employeeContribution: Optional[Decimal]
    domesticPartnerPostTax: Optional[Decimal]
    imputedIncome: Optional[Decimal]
    companyContribution: Optional[Decimal]
