# This workflow will install dependencies and create a build suitable
# to be used in an AWS Lambda Layer.
#
# Creates a build.zip and  releases it into lambda layer.
#
# A new version of the layer will be created whenever we trigger this
# workflow.


name: Build Lambda Layer

# For now, keeping it manual dispatch.
on: [workflow_dispatch]

jobs:
  
  deploy:
    name: Upload Layer to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # For more info: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Zip it all up
        run: zip --quiet -r flux-sdk.zip .
          
      - name: Publish Lambda layer from zip
        run: |
            aws lambda publish-layer-version --layer-name flux_sdk --zip-file flux-sdk.zip --compatible-runtimes python3.8
